sh for 11b
huggingface/setfit pull request #74
Opened 2022-09-30 03:35 UTC by eunseojo

2022-09-30 09:20 UTC, lewtun reviewed
Thanks for adding this script @eunseojo ! Can you please add some basic instructions to the README on how to run it?

2022-10-03 07:42 UTC, danielkorat requested changes
Thanks you @eunseojo great work!
Please drop the "(3 Billion)" from the README title.
Please also add a description of the two T-Few versionד at the top of the README. Something like:
"T-Few comes in 2 versions: one with a 3 billion (3B) base model, and one with an 11 billion (11B) base model.

2022-10-03 07:42 UTC, danielkorat commented on scripts/tfew/README.md
> +To run `T-Few` with the 11 billion base model run:
Please change all of these instances to `T-Few` (3B) or `T-Few` (11B).

2022-10-03 11:20 UTC, danielkorat approved these changes

2022-10-03 11:24 UTC, merged